In [1]:
import tensorflow as tf 
import numpy as np 

# data1 = tf.constant(np.arange(24).reshape(2,3,4), dtype='float64')
# print(data1)
# attention_mask = tf.constant([[1, 1 ,0], [1, 0, 0]], dtype='float64')
# mat = tf.linalg.diag(attention_mask)
# print(mat)
# print(data1.shape, mat.shape)
# mat1 = tf.matmul(mat, data1)
# print(mat1)
# data_tf = tf.reduce_sum(attention_mask, axis=1)
# # data_tf = tf.reduce_sum(mat1, axis=1)
# print(data_tf)

data1 = tf.constant(np.arange(2, 10).reshape(2, 4), dtype='float32')
print(data1)

data2 = tf.constant([[1], [2]], dtype='float32')
print(data2)

print(data1/data2)

tf.Tensor(
[[2. 3. 4. 5.]
 [6. 7. 8. 9.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1.]
 [2.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[2.  3.  4.  5. ]
 [3.  3.5 4.  4.5]], shape=(2, 4), dtype=float32)


In [3]:
data1 = tf.constant(np.arange(24).reshape(2,3,4), dtype='float64')

In [4]:
data1

<tf.Tensor: shape=(2, 3, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])>

In [8]:
tf.reduce_sum(data1, axis=2)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 6., 22., 38.],
       [54., 70., 86.]])>

In [9]:
data1[:1]

<tf.Tensor: shape=(1, 3, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]])>